version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:13
    env_file: 
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - gorm_postgres_network 
  go:
    container_name: go
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./
        target: /go/app
    command: go run main.go
    networks:
      - gorm_postgres_network
    ports:
      - "8080:8080"
        
volumes:
  gorm_postgres_volume:
    name: gorm_postgres_network

networks:
  gorm_postgres_network:
    external: true